apiVersion: apps/v1
kind: Deployment
metadata:
  name: 10-frontend-deployment
  labels:
    app: 10-frontend
    organizer: wipcamp10
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 10-frontend
      tier: frontend
      organizer: wipcamp10
  template:
    metadata:
      labels:
        app: 10-frontend
        tier: frontend
        organizer: wipcamp10
    spec:
      containers:
      - name: 10-frontend
        image: registry.wip.camp/10-frontend
        ports:
        - containerPort: 3000